version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2010
      POSTGRES_DB: eiasiscon
      POSTGRES_ENCODING: UTF-8
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: always
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: albertiano.net@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 2010
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "80:80"
    networks:
      - postgres
    restart: always

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin: