version: '3.7'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2010
      POSTGRES_DB: eiasiscon
      POSTGRES_ENCODING: UTF-8
      PGDATA: /var/lib/postgresql/data
    volumes:
       - db_data:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      - app
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: albertiano.net@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 2010
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
    networks:
      - app

  graphql-engine:
    container_name: graphql_container
    image: hasura/graphql-engine:v1.1.1
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:2010@postgres:5432/eiasiscon
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  db_data:
  pgadmin: